### ISSUE TITLE
API gives a "Fail to parse SDF String" with SDF files from PubChem

### ISSUE THREAD

**Issue by trikaloudis** [moltools/CineMol#1]
It works with other SDF files, e.g. from CHEBI.

**Comment by justinjjvanderhooft** [comment]
It *should* work with any sdf, also downloaded from Pubchem. Could you share the sdf that gave a parsing error?

**Comment by davidmeijer** [comment]
This could be a bug in parsing the counts line -- which I just noticed. Let me fix that.

**Comment by davidmeijer** [comment]
I have implemented a fix with [commit 8fdf3e5](https://github.com/moltools/CineMol/commit/8fdf3e5c36bcf534f824a7949d65e71ad21dbd73). @trikaloudis could you check if your input file now works?
