### ISSUE TITLE
ValueError: mutable default <class 'cinemol.style.Color'> for field outline_color is not allowed: use default_factory

### ISSUE THREAD

**Issue by iribirii** [moltools/CineMol#7]
I just installed cinemol and got this error message regardless of the command I try, even when running `python3 -m cinemol --help`

Any idea if this is a problem of my local distribution/libraries or if it is general?
![image](https://github.com/moltools/CineMol/assets/63478598/d943e765-9ffb-4488-bb84-272339a8cdbf)

**Comment by davidmeijer** [comment]
Hi! Thank you for reaching out and bringing this to my attention. It seems there was a bug in the code for Python 3.11 and 3.12. I have fixed this in the latest version 1.0.1 which you can install as `pip install cinemol==1.0.1`. Could you let me know if this solves your issue?

**Comment by iribirii** [comment]
it does indeed fix the issue, thank you very much!
